### ISSUE TITLE
android mp4播放不了

### ISSUE THREAD

**Issue by kangleblue** [tkzcfc/Kurumi#1]
你好，我有个mp4视频文件 ，播放不了，请问 你这边 是怎么播放成功的

https://user-images.githubusercontent.com/65843196/155956739-fb796933-98fd-416d-b8ec-76f36fa48556.mp4

呢，麻烦帮忙看看，我的 ffmpeg 版本是4.0.6

**Comment by tkzcfc** [comment]
Windows平台？

**Comment by kangleblue** [comment]
@tkzcfc 谢谢 我这边解决了

**Comment by kangleblue** [comment]
请教您，视频倍数播放 怎么实现呢

**Comment by tkzcfc** [comment]
只是加速画面的话  加快帧读取速度就行了吧    音频加速的话我也不清楚
